spring:
  # kafka配置
  kafka:
    bootstrap-servers: 127.0.0.1:9092
    consumer:
      group-id: myGroup
      auto-commit-interval: 1000
      enable-auto-commit: true
      auto-offset-reset: earliest
      max-poll-records: 200
      session-timeout: 30000
    producer:
      retries: 3
      batch-size: 10

  redis:
    host: 127.0.0.1
    port: 6379
    password: 123456
    jedis:
      pool:
        max-wait: 60000
        max-active: 200
        min-idle: 100
        max-idle: 100


